name: cicd

on:
    push:
        branches-ignore: [ga-ignore-*]
    pull_request:
        branches-ignore: [ga-ignore-*]

jobs:

    coding-style:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/epitech/coding-style-checker:latest
        steps:

            - name: Checkout Git repository
              uses: actions/checkout@v4

            - name: run coding style
              run: check.sh $(pwd) $(pwd)

            - name: report banana result
              run: |
                NB_ERRORS=$(cat coding-style-reports.log | wc -l)
                if [ $NB_ERRORS -gt 0 ]; then
                    ERROR=$(cat coding-style-reports.log)
                    echo "::error title=$NB_ERROR errors found::$ERROR"
                    exit 1
                else
                    exit 0
                fi

    compile:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout Git repository
              uses: actions/checkout@v4

            - name: compile project
              run: make
            
            - name: check binary
              run: |
                if [ ! -f ./swapupcase ]; then
                    echo "::error title=swapupcase::Binary not found"
                    exit 1
                else
                    exit 0
                fi

    run-tests:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/epitechcontent/epitest-docker:latest
        needs: [compile, coding-style]
        steps:

            - name: Checkout Git repository
              uses: actions/checkout@v4

            - name: compile unit tests
              run: make compile_tests

            - name: run tests
              run: ./unit_testing
            
            - name: run integration tests
              run: ./integration_testing