name: cicd

on:
    push:
        branches-ignore: [ga-ignore-*]
    pull_request:
        branches-ignore: [ga-ignore-*]

jobs:

    coding-style:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/epitech/coding-style-checker:latest
        steps:

            - name: Checkout Git repository
              uses: actions/checkout@v4

            - name: run coding style
              run: check.sh ${pwd} ${pwd}

            - name: report banana result
              run: |
                NB_ERRORS=$(cat coding-style-reports.log | wc -l)
                if [ $NB_ERRORS -gt 0 ]; then
                    ERROR=$(cat coding-style-reports.log)
                    echo "::error title=$NB_ERROR errors found::$ERROR"
                    exit 1
                else
                    exit 0
                fi